title: Steffen's random thoughts
description:
  This my personal blog, where I post about things that I do and find interesting.
  All posts and thoughts on this blog are solely my opinion and are not related to my employer.
github_username:  sscheib
github: [metadata]
repository: 'sscheib/sscheib.github.io'

remote_theme: jekyll/minima@v2.5.1
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jemoji
  - jekyll-spaceship
  - jekyll-gist

header_pages:
  - index.md
  - about.md

minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/sscheib" }
    - { linkedin: linkedin,  user_url: "https://linkedin.com/in/sscheib" }

author: Steffen Scheib

jekyll-spaceship:
  mermaid-processor:
    mode: 'pre-fetch'
    config:
      theme: 'base'
