remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: Steffen Scheib - personal blog
description: This is my personal blog. All thoughts and posts are not related to my current or former employer in any way.
