---
name: 'markdownlint'
on:
  pull_request:
    branches: ['main']
  workflow_dispatch: {}

jobs:
  build:
    name: 'markdownlint-cli'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'markdownlint-cli'
        uses: 'nosborn/github-action-markdown-cli@v3.3.0'
        with:
          files: './_posts/'
          config_file: '.markdownlint.yml'
          dot: false
...
