---
name: 'yamllint'
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: ['main']
  workflow_dispatch: {}
jobs:
  yamllint:
    name: 'yamllint'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v3'

      - name: 'Run yamllint'
        uses: 'karancode/yamllint-github-action@master'
        with:
          yamllint_config_filepath: '.yamllint'
...
